name: Snapshot Build

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "**/*.md"
      - "**/LICENSE"
  workflow_dispatch:

permissions:
  contents: write
  checks: write
  statuses: write

jobs:

  snapshot:

    name: Snapshot Build
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Update dependencies
        run: cargo update

      - name: Set up Rust toolchain
        env:
          RUSTUP_TOOLCHAIN: stable
        uses: moonrepo/setup-rust@v0
        with:
          cache: true
          cache-target: release
          targets: x86_64-pc-windows-msvc
          profile: minimal

      - name: Build Windows CLI
        env:
          RUSTFLAGS: "-Ctarget-cpu=x86-64-v2 -Ctarget-feature=+crt-static"
        run: cargo build --release --target x86_64-pc-windows-msvc --bin wordstat

      - name: Build Windows GUI
        env:
          RUSTFLAGS: "-Ctarget-cpu=x86-64-v2 -Ctarget-feature=+crt-static"
        run: cargo build --release --target x86_64-pc-windows-msvc --bin wordstat-gui --no-default-features --features gui

      - name: Collect executables
        run: |
          mv target/x86_64-pc-windows-msvc/release/wordstat.exe wordstat.exe
          mv target/x86_64-pc-windows-msvc/release/wordstat-gui.exe wordstat-gui.exe

      - name: Upload release
        uses: Systemcluster/actions@release-github-v0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: snapshot
          name:  Snapshot
          prerelease: false
          files: |
            wordstat.exe
            wordstat-gui.exe
